apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: solace-dc-pvc
  namespace: solace
spec:
  storageClassName: "gp3"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
