apiVersion: v1
kind: Service
metadata:
  name: solacedc
  namespace: solace
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  selector:
    app: solacedc
  ports:
    - name: web
      port: 8080
      targetPort: 8080
    - name: smf
      port: 55555
      targetPort: 55555
    - name: ssh
      port: 2222
      targetPort: 2222
    - name: ssl
      port: 1943
      targetPort: 1943
