apiVersion: v1
kind: Service
metadata:
  name: solacedc
  namespace: solace
spec:
  type: LoadBalancer
  selector:
    app: solacedc
  ports:
    - name: web
      port: 8080
      targetPort: 8080
      protocol: TCP

    - name: smf
      port: 55555
      targetPort: 55555
      protocol: TCP

    - name: ssh
      port: 2222
      targetPort: 2222
      protocol: TCP

    - name: ssl
      port: 1943
      targetPort: 1943
      protocol: TCP
